### ISSUE TITLE
Test rebuilds: What exactly do they mean and where are they?

### ISSUE THREAD

**Issue by nteodosio** [canonical/ubuntu-mir#59]
From the template:

```
RULE: - if there has been an archive test rebuild that has occurred more recently
RULE:   than the last upload, the package must have rebuilt successfully
TODO-A: - The package has been built in the archive more recently than the last
TODO-A:   test rebuild
TODO-B: - The package successfully built during the most recent test rebuild
TODO-C: - The package was test rebuilt in PPA or sbuild recently (provide link/logs)
```

But it does not define "test rebuil[td]" nor does it provide a way to find them.

Is a build in a PPA of the said package means that "the package was test rebuilt in a PPA"? What does "test" mean here? If the package was built recently in the Launchpad universe (e.g. [this was built yesterday](https://launchpad.net/ubuntu/+source/xdg-terminal-exec/0.10.0-1/+build/28571265)), is a PPA or sbuild really necessary? If not, can you extend TODO-C accordingly?

**Comment by slyon** [comment]
Test rebuilds are usually announced on ubuntu-devel@, ubuntu-devel-announce@ and other mailing lists by the Foundations team, e.g.: https://lists.ubuntu.com/archives/ubuntu-devel-announce/2024-January/001342.html

Most recently they have been published by @ginggs on https://people.canonical.com/~ginggs/ftbfs-report/

**Comment by didrocks** [comment]
As @slyon said, this is announced on the devel ML. Maybe we can phrase out something around it? The issue is that the report is always under some people's account on people.canonical.com (could be @doko, could be @ginggs…) and so we can’t use a permalink there.

Maybe it will be the correct time to have some kind of url somewhere for the last test rebuild which can redirect to some people's page? That way, we always have an unique place to look at for "what was the last test rebuild result". Or maybe ensuring the test rebuilds are put in a more official place, like we have for proposed-migration, ubuntu-desktop updates and release bug tracking?

**Comment by cpaelzer** [comment]
I think most helpful things have been said.
I'd not wait/gate on changing the hosting of these results but in general propose to make the rule/todo statements more clear what we want and why we want it - that will eliminate most uncertainties already.

There is more than uncertainty ...
- We actually want links each time
- We should change the time relation to the rebuild to just a time (I'll pick 3 months) 
- We need to split PPA and sbuild as the reasons are different
- ...

I'll propose a PR in a bit
