### ISSUE TITLE
let us fully soft re-evaluate any requests that have no trackable bug

### ISSUE THREAD

**Issue by cpaelzer** [canonical/ubuntu-mir#74]
If sources have been in main kind of forever, we get into cases where we have no evidence when/how it was checked against.
Furthermore we have raised the bar and there might be helpful new suggestions.

To be pragmatic and not block, all but really sinister issues should be "recommended" (and not "required").

Still that would over time make sure the dark past get trackable and allow us to suggest good modern guidance on some very old components.

**Comment by cpaelzer** [comment]
The intended trigger for now should be "source rename" which makes them pop up on our radar.

We might later (but not now) add re-evaluating what is in main, but has no bug at all - but not yet.

**Comment by dviererbe** [comment]
I like the idea of reviewing old packages in main without MIR bug too. Just some thoughts for consideration on this topic: During the sprint in The Hague we (Foundations) sat down for an hour and looked through the packages we own. In that time we managed to look through 442 of the 1011 packages we are assigned to in Launchpad. Of the 442 packages we managed to look through 238 did not have an MIR bug. Imagining we would review one package every week, just reviewing 238 packages would take 4.5 years to review. There probably are some false negatives, because some packages have an MIR wiki entry instead of an MIR launchpad bug, but scaling this approximation to all packages in main this seems to look like a decade-project to me :/ 

Which is NOT a reason to NOT start! Just wanted to share our findings.

_(Sorry for not bringing this up during the MIR meeting, but I was distracted during the end)_

**Comment by cpaelzer** [comment]
You are right @dviererbe that is not far off my expectation. But that is why we want to introduce it slowly, see how it works and can then consider if we want and can spend more to fight the past. Maybe there can be a lighter, still useful form of it once we've experience from a few of those cases.
